name: Deploy to ECS

on:
  push:
    branches:
      - master  # Specify the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Deploy to ECS
        run: |
          ECS_CLUSTER="ecs-fargate-cluster"  # Replace with your ECS cluster name
          ECS_SERVICE="my-app-service"  # Replace with your ECS service name
          CONTAINER_NAME="webserver"       # Replace with your container name

          # Update ECS service with the new image
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment

